// Snapshot of original indexed vocabulary for migration checks.
const words = [
  // ── Cũ (index 0–29, giữ nguyên thứ tự) ──
  { ko: '안녕하세요', roman: 'annyeonghaseyo', meaning: 'Xin chào', topic: 'chào hỏi' },
  { ko: '감사합니다', roman: 'gamsahamnida', meaning: 'Cảm ơn', topic: 'chào hỏi' },
  { ko: '네', roman: 'ne', meaning: 'Vâng / Có', topic: 'giao tiếp' },
  { ko: '아니요', roman: 'aniyo', meaning: 'Không', topic: 'giao tiếp' },
  { ko: '미안해요', roman: 'mianhaeyo', meaning: 'Xin lỗi', topic: 'chào hỏi' },
  { ko: '사랑해요', roman: 'saranghaeyo', meaning: 'Tôi yêu bạn', topic: 'tình cảm' },
  { ko: '보고 싶어요', roman: 'bogo sipeoyo', meaning: 'Tôi nhớ bạn', topic: 'tình cảm' },
  { ko: '맛있어요', roman: 'masisseoyo', meaning: 'Ngon quá', topic: 'ăn uống' },
  { ko: '좋아요', roman: 'joayo', meaning: 'Tốt / Thích', topic: 'giao tiếp' },
  { ko: '물', roman: 'mul', meaning: 'Nước', topic: 'ăn uống' },
  { ko: '밥', roman: 'bap', meaning: 'Cơm', topic: 'ăn uống' },
  { ko: '이름', roman: 'ireum', meaning: 'Tên', topic: 'bản thân' },
  { ko: '안녕', roman: 'annyeong', meaning: 'Chào / Tạm biệt (thân mật)', topic: 'chào hỏi' },
  { ko: '잘 자요', roman: 'jal jayo', meaning: 'Ngủ ngon', topic: 'chào hỏi' },
  { ko: '괜찮아요', roman: 'gwaenchanayo', meaning: 'Không sao / Ổn mà', topic: 'giao tiếp' },
  { ko: '주세요', roman: 'juseyo', meaning: 'Làm ơn cho tôi…', topic: 'giao tiếp' },
  { ko: '커피', roman: 'keopi', meaning: 'Cà phê', topic: 'ăn uống' },
  { ko: '차', roman: 'cha', meaning: 'Trà', topic: 'ăn uống' },
  { ko: '우유', roman: 'uyu', meaning: 'Sữa', topic: 'ăn uống' },
  { ko: '빵', roman: 'ppang', meaning: 'Bánh mì', topic: 'ăn uống' },
  { ko: '사과', roman: 'sagwa', meaning: 'Quả táo', topic: 'ăn uống' },
  { ko: '친구', roman: 'chingu', meaning: 'Bạn bè', topic: 'bản thân' },
  { ko: '가족', roman: 'gajok', meaning: 'Gia đình', topic: 'gia đình' },
  { ko: '집', roman: 'jip', meaning: 'Nhà', topic: 'nơi chốn' },
  { ko: '학교', roman: 'hakgyo', meaning: 'Trường học', topic: 'nơi chốn' },
  { ko: '오늘', roman: 'oneul', meaning: 'Hôm nay', topic: 'thời gian' },
  { ko: '내일', roman: 'naeil', meaning: 'Ngày mai', topic: 'thời gian' },
  { ko: '행복', roman: 'haengbok', meaning: 'Hạnh phúc', topic: 'tình cảm' },
  { ko: '예뻐요', roman: 'yeppeoyo', meaning: 'Đẹp quá', topic: 'tình cảm' },
  { ko: '고마워요', roman: 'gomawoyo', meaning: 'Cảm ơn (gần gũi)', topic: 'chào hỏi' },
  // ── Mới: chào hỏi (30–35) ──
  { ko: '만나서 반가워요', roman: 'mannaseo bangawoyo', meaning: 'Rất vui được gặp bạn', topic: 'chào hỏi' },
  { ko: '잘 지냈어요?', roman: 'jal jinaesseoyo?', meaning: 'Bạn có khỏe không?', topic: 'chào hỏi' },
  { ko: '잘 지냈어요', roman: 'jal jinaesseoyo', meaning: 'Tôi vẫn khỏe', topic: 'chào hỏi' },
  { ko: '또 봐요', roman: 'tto bwayo', meaning: 'Hẹn gặp lại', topic: 'chào hỏi' },
  { ko: '오랜만이에요', roman: 'oraenmanieyo', meaning: 'Lâu rồi không gặp', topic: 'chào hỏi' },
  { ko: '잠깐만요', roman: 'jamkkanmanyo', meaning: 'Chờ một chút', topic: 'chào hỏi' },
  // ── Mới: bản thân (36–41) ──
  { ko: '저', roman: 'jeo', meaning: 'Tôi (lịch sự)', topic: 'bản thân' },
  { ko: '나', roman: 'na', meaning: 'Tôi (thân mật)', topic: 'bản thân' },
  { ko: '이름이 뭐예요?', roman: 'ireumi mwoyeyo?', meaning: 'Tên bạn là gì?', topic: 'bản thân' },
  { ko: '학생이에요', roman: 'haksaengieyo', meaning: 'Tôi là học sinh', topic: 'bản thân' },
  { ko: '한국 사람이에요?', roman: 'hanguk saramieyo?', meaning: 'Bạn là người Hàn Quốc?', topic: 'bản thân' },
  { ko: '베트남 사람이에요', roman: 'beteunam saramieyo', meaning: 'Tôi là người Việt Nam', topic: 'bản thân' },
  // ── Mới: gia đình (42–51) ──
  { ko: '엄마', roman: 'eomma', meaning: 'Mẹ', topic: 'gia đình' },
  { ko: '아빠', roman: 'appa', meaning: 'Bố', topic: 'gia đình' },
  { ko: '오빠', roman: 'oppa', meaning: 'Anh trai (em gái gọi)', topic: 'gia đình' },
  { ko: '언니', roman: 'eonni', meaning: 'Chị gái (em gái gọi)', topic: 'gia đình' },
  { ko: '남동생', roman: 'namdongsaeng', meaning: 'Em trai', topic: 'gia đình' },
  { ko: '여동생', roman: 'yeodongsaeng', meaning: 'Em gái', topic: 'gia đình' },
  { ko: '할머니', roman: 'halmeoni', meaning: 'Bà nội / ngoại', topic: 'gia đình' },
  { ko: '할아버지', roman: 'harabeoji', meaning: 'Ông nội / ngoại', topic: 'gia đình' },
  { ko: '남자친구', roman: 'namjachingu', meaning: 'Bạn trai', topic: 'gia đình' },
  { ko: '여자친구', roman: 'yeojachingu', meaning: 'Bạn gái', topic: 'gia đình' },
  // ── Mới: ăn uống (52–59) ──
  { ko: '먹어요', roman: 'meogeoyo', meaning: 'Ăn', topic: 'ăn uống' },
  { ko: '마셔요', roman: 'masyeoyo', meaning: 'Uống', topic: 'ăn uống' },
  { ko: '배고파요', roman: 'baegopayo', meaning: 'Tôi đói', topic: 'ăn uống' },
  { ko: '배불러요', roman: 'baebulleoyo', meaning: 'Tôi no rồi', topic: 'ăn uống' },
  { ko: '맛없어요', roman: 'maseopsseoyo', meaning: 'Không ngon', topic: 'ăn uống' },
  { ko: '음식', roman: 'eumsik', meaning: 'Đồ ăn / Thức ăn', topic: 'ăn uống' },
  { ko: '식당', roman: 'sikdang', meaning: 'Nhà hàng / Quán ăn', topic: 'ăn uống' },
  { ko: '얼마예요?', roman: 'eolmayeyo?', meaning: 'Bao nhiêu tiền?', topic: 'ăn uống' },
  // ── Mới: nơi chốn (60–69) ──
  { ko: '여기', roman: 'yeogi', meaning: 'Đây / Ở đây', topic: 'nơi chốn' },
  { ko: '저기', roman: 'jeogi', meaning: 'Kia / Ở kia', topic: 'nơi chốn' },
  { ko: '어디', roman: 'eodi', meaning: 'Ở đâu?', topic: 'nơi chốn' },
  { ko: '병원', roman: 'byeongwon', meaning: 'Bệnh viện', topic: 'nơi chốn' },
  { ko: '편의점', roman: 'pyeonuijeom', meaning: 'Cửa hàng tiện lợi', topic: 'nơi chốn' },
  { ko: '카페', roman: 'kape', meaning: 'Quán cà phê', topic: 'nơi chốn' },
  { ko: '지하철', roman: 'jihacheol', meaning: 'Tàu điện ngầm', topic: 'nơi chốn' },
  { ko: '버스', roman: 'beoseu', meaning: 'Xe buýt', topic: 'nơi chốn' },
  { ko: '화장실', roman: 'hwajangsil', meaning: 'Nhà vệ sinh', topic: 'nơi chốn' },
  { ko: '공항', roman: 'gonghang', meaning: 'Sân bay', topic: 'nơi chốn' },
  // ── Mới: thời gian (70–78) ──
  { ko: '지금', roman: 'jigeum', meaning: 'Bây giờ', topic: 'thời gian' },
  { ko: '어제', roman: 'eoje', meaning: 'Hôm qua', topic: 'thời gian' },
  { ko: '아침', roman: 'achim', meaning: 'Buổi sáng', topic: 'thời gian' },
  { ko: '점심', roman: 'jeomsim', meaning: 'Buổi trưa', topic: 'thời gian' },
  { ko: '저녁', roman: 'jeonyeok', meaning: 'Buổi tối', topic: 'thời gian' },
  { ko: '주말', roman: 'jumal', meaning: 'Cuối tuần', topic: 'thời gian' },
  { ko: '월요일', roman: 'woryoil', meaning: 'Thứ Hai', topic: 'thời gian' },
  { ko: '일요일', roman: 'iryoil', meaning: 'Chủ Nhật', topic: 'thời gian' },
  { ko: '몇 시예요?', roman: 'myeot siyeyo?', meaning: 'Mấy giờ rồi?', topic: 'thời gian' },
  // ── Mới: sinh hoạt (79–88) ──
  { ko: '가요', roman: 'gayo', meaning: 'Đi', topic: 'sinh hoạt' },
  { ko: '와요', roman: 'wayo', meaning: 'Đến / Tới', topic: 'sinh hoạt' },
  { ko: '해요', roman: 'haeyo', meaning: 'Làm', topic: 'sinh hoạt' },
  { ko: '봐요', roman: 'bwayo', meaning: 'Xem / Nhìn', topic: 'sinh hoạt' },
  { ko: '자요', roman: 'jayo', meaning: 'Ngủ', topic: 'sinh hoạt' },
  { ko: '일어나요', roman: 'ireonayo', meaning: 'Thức dậy', topic: 'sinh hoạt' },
  { ko: '씻어요', roman: 'ssisseoyo', meaning: 'Rửa / Tắm', topic: 'sinh hoạt' },
  { ko: '공부해요', roman: 'gongbuhaeyo', meaning: 'Học bài', topic: 'sinh hoạt' },
  { ko: '일해요', roman: 'ilhaeyo', meaning: 'Làm việc', topic: 'sinh hoạt' },
  { ko: '쉬어요', roman: 'swieyo', meaning: 'Nghỉ ngơi', topic: 'sinh hoạt' },
  // ── Mới: tình cảm (89–94) ──
  { ko: '사랑해', roman: 'saranghae', meaning: 'Yêu (thân mật)', topic: 'tình cảm' },
  { ko: '보고 싶어', roman: 'bogo sipeo', meaning: 'Nhớ bạn (thân mật)', topic: 'tình cảm' },
  { ko: '걱정하지 마요', roman: 'geokjeonghaji mayo', meaning: 'Đừng lo lắng', topic: 'tình cảm' },
  { ko: '힘내요', roman: 'himnaeyo', meaning: 'Cố lên!', topic: 'tình cảm' },
  { ko: '잘했어요', roman: 'jalhaesseoyo', meaning: 'Làm tốt lắm!', topic: 'tình cảm' },
  { ko: '항상', roman: 'hangsang', meaning: 'Luôn luôn', topic: 'tình cảm' },
  // ── Mới: số đếm (95–104) ──
  { ko: '하나', roman: 'hana', meaning: 'Một (Hàn thuần)', topic: 'số đếm' },
  { ko: '둘', roman: 'dul', meaning: 'Hai (Hàn thuần)', topic: 'số đếm' },
  { ko: '셋', roman: 'set', meaning: 'Ba (Hàn thuần)', topic: 'số đếm' },
  { ko: '넷', roman: 'net', meaning: 'Bốn (Hàn thuần)', topic: 'số đếm' },
  { ko: '다섯', roman: 'daseot', meaning: 'Năm (Hàn thuần)', topic: 'số đếm' },
  { ko: '일', roman: 'il', meaning: '1 (Hán-Hàn)', topic: 'số đếm' },
  { ko: '이', roman: 'i', meaning: '2 (Hán-Hàn)', topic: 'số đếm' },
  { ko: '삼', roman: 'sam', meaning: '3 (Hán-Hàn)', topic: 'số đếm' },
  { ko: '사', roman: 'sa', meaning: '4 (Hán-Hàn)', topic: 'số đếm' },
  { ko: '오', roman: 'o', meaning: '5 (Hán-Hàn)', topic: 'số đếm' },
  // ── Mới: màu sắc (105–110) ──
  { ko: '빨간색', roman: 'ppalgansaek', meaning: 'Màu đỏ', topic: 'màu sắc' },
  { ko: '파란색', roman: 'paransaek', meaning: 'Màu xanh lam', topic: 'màu sắc' },
  { ko: '노란색', roman: 'noransaek', meaning: 'Màu vàng', topic: 'màu sắc' },
  { ko: '하얀색', roman: 'hayansaek', meaning: 'Màu trắng', topic: 'màu sắc' },
  { ko: '검은색', roman: 'geomeunsaek', meaning: 'Màu đen', topic: 'màu sắc' },
  { ko: '분홍색', roman: 'bunhongsaek', meaning: 'Màu hồng', topic: 'màu sắc' },
  // ── Mới: câu thực hành (111–119) ──
  { ko: '저는 학생이에요', roman: 'jeoneun haksaengieyo', meaning: 'Tôi là học sinh', topic: 'ngữ pháp' },
  { ko: '이것은 뭐예요?', roman: 'igeoseun mwoyeyo?', meaning: 'Cái này là gì?', topic: 'ngữ pháp' },
  { ko: '저는 밥을 먹어요', roman: 'jeoneun babeul meogeoyo', meaning: 'Tôi ăn cơm', topic: 'ngữ pháp' },
  { ko: '어디에 가요?', roman: 'eodie gayo?', meaning: 'Bạn đi đâu?', topic: 'ngữ pháp' },
  { ko: '뭐 먹을까요?', roman: 'mwo meogeulkkayo?', meaning: 'Ăn gì nhỉ?', topic: 'ngữ pháp' },
  { ko: '안 먹어요', roman: 'an meogeoyo', meaning: 'Không ăn', topic: 'ngữ pháp' },
  { ko: '저도요', roman: 'jeodoyo', meaning: 'Tôi cũng vậy', topic: 'giao tiếp' },
  { ko: '맞아요', roman: 'majayo', meaning: 'Đúng rồi!', topic: 'giao tiếp' },
  { ko: '오늘 날씨가 좋아요', roman: 'oneul nalssiga joayo', meaning: 'Hôm nay trời đẹp', topic: 'ngữ pháp' }
];

module.exports = words;
